import { Room, Coordinates } from "../../types";
import { coordRange } from "../../utils";

export const BarGikoSquareV2Room: Room = {
    id: "bar_giko_square_v2",
    group: "agora_road",
    scale: 1,
    size: { x: 24, y: 27 },
    originCoordinates: { x: -201, y: 640 },
    spawnPoint: "up",
    backgroundImageUrl: "rooms/bar_giko_square_v2/background.svg",
    objects: [
        { x:  9, y:  5, offset: { x:    157, y:  543 }, url: "mall_arch_back.svg" },
        { x:  14, y:  0, offset: { x:    197, y:  541 }, url: "mall_arch_front.svg" },

        { x:  0, y:  9, offset: { x:    160, y:  199 }, url: "koban_with_poster.svg" },
        { x: 15, y: 23, offset: { x: 1319, y:  259 }, url: "bar_giko_with_roof.svg" },
        { x: 16, y: 22, offset: { x: 1320, y:  438 }, url: "bar_giko_sign.svg" },
        { x: 11, y: 16, offset: { x:  820, y:  422 }, url: "fountain.svg" },
        { x:  6, y: 22, offset: { x:  919, y:  232 }, url: "bench.svg" },
        { x: 19, y:  14, offset: { x:  1149, y:  491 }, url: "street_light_left.svg" },
        { x: 14, y: 22, offset: { x: 1270, y:  226 }, url: "street_light_left.svg" },
        { x:  14, y:  9, offset: { x:  750, y:  491 }, url: "street_light_right.svg" },
    ],
    sit: [
        { x:  6, y: 22 },
        { x:  7, y: 22 },
        { x:  8, y: 22 },
        // fountain
        { x: 13, y: 15 },
        { x: 13, y: 16 },
        { x: 11, y: 14 },
        { x: 12, y: 14 },
    ],
    blocked: [
        // Koban quarter
        { x:  3, y:  9 },
        { x:  2, y:  9 },
        { x:  1, y:  9 },
        { x:  0, y:  9 },
        { x:  3, y:  10 },
        { x:  3, y:  11 },
        { x:  3, y:  12 },
        { x:  3, y:  13 },
        { x:  2, y:  13 },
        { x:  1, y:  13 },
        { x:  0, y:  13 },
        { x:  0, y:  7 },
        { x:  1, y:  7 },
        { x:  2, y:  7 },
        { x:  3, y:  7 },
        { x:  4, y:  7 },
        { x:  5, y:  7 },
        { x:  6, y:  8 },
        { x:  7, y:  8 },
        { x:  8, y:  8 },
        { x:  8, y:  7 },
        { x:  8, y:  6 },

        // Yoshinoya quarter
        { x:  0, y:  18 },
        { x:  1, y:  18 },
        { x:  2, y:  18 },
        { x:  3, y:  18 },
        { x:  3, y:  19 },
        { x:  3, y:  20 },
        { x:  3, y:  21 },
        { x:  3, y:  22 },
        { x:  4, y:  23 },
        { x:  5, y:  23 },
        { x:  6, y:  23 },
        { x:  7, y:  23 },
        { x:  8, y:  23 },
        { x:  8, y:  24 },
        { x:  8, y:  25 },
        { x:  8, y:  26 },

        // Bar Giko quarter
        { x:  15, y:  23 },
        { x:  15, y:  24 },
        { x:  15, y:  25 },
        { x:  15, y:  26 },
        { x:  16, y:  23 },
        { x:  17, y:  23 },
        { x:  18, y:  23 },
        { x:  19, y:  23 },
        { x:  20, y:  22 },
        { x:  20, y:  21 },
        { x:  20, y:  20 },
        { x:  20, y:  19 },
        { x:  20, y:  18 },
        { x:  21, y:  18 },
        { x:  22, y:  18 },
        { x:  23, y:  18 },

        // Bar Giko sign
        { x:  16, y:  22 },

        // Mall quarter
        { x:  9, y:  5 },
        { x:  9, y:  4 },
        { x:  9, y:  3 },
        { x:  9, y:  2 },
        { x:  9, y:  1 },
        { x:  10, y:  0 },
        { x:  10, y:  1 },
        { x:  13, y:  0 },
        { x:  14, y:  1 },
        { x:  14, y:  2 },
        { x:  14, y:  3 },
        { x:  14, y:  4 },
        { x:  14, y:  5 },

        // Empty quarter
        { x:  23, y:  13 },
        { x:  22, y:  13 },
        { x:  21, y:  13 },
        { x:  20, y:  13 },
        { x:  20, y:  12 },
        { x:  20, y:  11 },
        { x:  20, y:  10 },
        { x:  20, y:  9 },
        { x:  19, y:  8 },
        { x:  18, y:  8 },
        { x:  17, y:  8 },
        { x:  16, y:  8 },
        { x:  15, y:  8 },
        { x:  15, y:  7 },
        { x:  15, y:  6 },

        // Street lights
        { x:  14, y:  22 },
        { x: 14, y: 9 },
        { x: 19, y:  14 },

        // Fountain
        { x: 12, y: 15 },
        { x: 12, y: 16 },
        { x: 12, y: 17 },
        { x: 11, y: 15 },
        { x: 10, y: 16 },
        { x: 10, y: 15 },
        { x: 11, y: 17 },
    ],
    forbiddenMovements: [],
    doors: {
        up: { x: 11, y: 26, direction: "down", target: { roomId: "densha", doorId: "left_middle" } },
        bar_giko: { x: 17, y: 22, direction: "down", target: { roomId: "bar_giko", doorId: "stairs" } },
        yoshinoya: { x: 4, y: 20, direction: "right", target: { roomId: "yoshinoya", doorId: "door" } },
        left: { x: 0, y: 17, direction: "right", target: { roomId: "monachat", doorId: "door" } },
        right: { x: 23, y: 16, direction: "left", target: { roomId: "konbini", doorId: "door" } },
        office: { x: 5, y: 22, direction: "down", target: { roomId: "nerd_office", doorId: "door"} },
        bottom_left: {x: 17, y: 9, direction: "up", target: {roomId: "meganeya", doorId: "top_right"} },
        very_left: {x: 0, y: 8, direction: "right", target: { roomId: "kyougijou", doorId: "door"} },
        mall_left_top: {x: 11, y: 0, direction: "down", target: { roomId: "vapor_mall", doorId: "right_top"} },
        mall_left_bottom: {x: 12, y: 0, direction: "down", target: { roomId: "vapor_mall", doorId: "right_bottom"} },
    },
    streamSlotCount: 0,
};
