import { Room, Coordinates } from "../../types";
import { coordRange } from "../../utils";

export const VaporMallRoom: Room = {
    id: "vapor_mall",
    group: "agora_road",
    scale: 1,
    size: { x: 10, y: 25 },
    blockHeight: 35.5,
    blockWidth: 71.5,
    originCoordinates: { x: 1, y: 411 },
    spawnPoint: "right_top",
    backgroundImageUrl: "rooms/vapor_mall/mall.svg",
    backgroundColor: "#2EB3AC",
    objects: [
        { x: 5, y: 0, offset: { x: 189, y: 447 }, url: "barrier.svg" },
        { x: 6, y: 0, offset: { x: 225, y: 465 }, url: "barrier.svg" },
        { x: 9, y: 4, offset: { x: 465, y: 448 }, url: "ctrl.svg" },
        { x: 9, y: 1, offset: { x: 320, y: 417 }, url: "fountain.svg" },
        { x: 9, y: 8, offset: { x: 605, y: 179 }, url: "palm_(fresh_prince_of_bel_air).svg" },
        { x: 2, y: 1, offset: { x: 36, y: 232 }, url: "palm_(tall_king).svg" },

        { x: 9, y: 5, offset: { x: 501, y: 429 }, url: "space_bar_near_end.svg" },
        { x: 9, y: 6, offset: { x: 536, y: 410 }, url: "space_bar_middle.svg" },
        { x: 9, y: 7, offset: { x: 572, y: 392 }, url: "space_bar_middle.svg" },
        { x: 9, y: 8, offset: { x: 608, y: 376 }, url: "space_bar_far_end.svg" },

        { x: 9, y: 1, offset: { x: 787, y: 36 }, url: "music_player.svg" },
       // { x: 9, y: 8, offset: { x: 500, y: 376 }, url: "space_bar.svg" },

        { x: 2, y: 6, offset: { x: 501, y: 35.5 }, url: "wall_foreground.svg" },
    ],
    sit: [
        { x: 9, y: 4 },
        { x: 9, y: 5},
        { x: 9, y: 6 },
        { x: 9, y: 7 },
        { x: 9, y: 8 },
        { x: 1, y: 2 },
        { x: 1, y: 3 },
        { x: 1, y: 4 },
        { x: 1, y: 5 },
        { x: 1, y: 6 },
        { x: 1, y: 7 },
        { x: 2, y: 7 },
        { x: 3, y: 7 },
        { x: 3, y: 8 },
    ],
    blocked: [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 3, y: 0 },
        { x: 4, y: 0 },
        { x: 5, y: 0 },
        { x: 6, y: 0 },
        { x: 7, y: 0 },
        { x: 8, y: 0 },
        { x: 9, y: 0 },
        { x: 9, y: 1 },
        { x: 9, y: 2 },
        { x: 9, y: 3 },
        { x: 8, y: 1 },
        { x: 8, y: 2 },
        { x: 7, y: 1 },
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 0, y: 3 },
        { x: 0, y: 4 },
        { x: 0, y: 5 },
        { x: 0, y: 6 },
        { x: 0, y: 7 },
        { x: 0, y: 8 },
        { x: 0, y: 9 },
        { x: 0, y: 10 },
        { x: 1, y: 10 },
        { x: 2, y: 10 },
        { x: 3, y: 10 },
        { x: 4, y: 10 },
        { x: 7, y: 10 },
        { x: 8, y: 10 },
        { x: 9, y: 10 },
        { x: 5, y: 11 },
        { x: 6, y: 11 },
        { x: 1, y: 8 },
        { x: 1, y: 9 },
        { x: 2, y: 9 },
        { x: 3, y: 9 },
        { x: 7, y: 2 },
        { x: 7, y: 3 },
        { x: 8, y: 3 },
        { x: 1, y: 1 },
        { x: 1, y: 20 },
        { x: 1, y: 21 },
        { x: 1, y: 22 },
        { x: 1, y: 23 },
        { x: 2, y: 20 },
        { x: 2, y: 23 },
        { x: 3, y: 20 },
        { x: 3, y: 21 },
        { x: 3, y: 22 },
        { x: 3, y: 23 },
    ],
    forbiddenMovements: [
        { xFrom:  9, yFrom:  9, xTo:  9, yTo:  8 },
    ],
    doors: {
        right_top: { x: 5, y: 10, direction:null, target: { roomId: "bar_giko_square_v2", doorId: "mall_left_top" } },
        right_bottom: { x: 6, y: 10, direction:null, target: { roomId: "bar_giko_square_v2", doorId: "mall_left_bottom" } },
        helios: { x: 2, y: 8, direction:null, target: { roomId: "vapor_mall", doorId: "music_player_spawn" } },
        music_player_spawn: { x: 2, y: 22, direction:null, target: null},
        music_player_exit: { x: 2, y: 21, direction:null, target: { roomId: "vapor_mall", doorId: "right_top" } },
    },
    streamSlotCount: 8,
};
